# Class filter used for Austria field boundaries.
# Excluded classes are those that are not considered agricultural fields, e.g. forest, ecological protection areas.
# Notable exclusions: grassland, pasture, orchards, fruit trees, vineyards, grasses, flowers and ornamental plants, anything in the greenhouse, "protected cultivation".
# Notable inclusions: alfalfa, clover, berries, medicinal plants/herbs.
# Codes from https://raw.githubusercontent.com/maja601/EuroCrops/refs/heads/main/csvs/country_mappings/at_2021.csv

column: crop:code

include:
  - 635  # LUZERNE
  - 758  # AMARANTH
  - 691  # RÜBENVERMEHRUNG
  - 207  # BITTERLUPINEN
  - 119  # BUCHWEIZEN
  - 689  # LEINDOTTER
  - 120  # KANARIENSAAT
  - 623  # KICHERERBSEN
  - 633  # KLEE
  - 664  # KLEE / FELDGEMÜSE
  - 665  # KLEEGRAS / FELDGEMÜSE
  - 634  # KLEEGRAS
  - 172  # MAIS / KÄFERBOHNEN IN GETRENNTEN REIHEN
  - 131  # MAIS CORN-COB-MIX (CCM) / FELDGEMÜSE
  - 106  # MAIS CORN-COB-MIX (CCM)
  - 774  # DURCHWACHSENE SILPHIE
  - 513  # FRÜHKARTOFFELN
  - 529  # FRÜHKARTOFFELN / BUCHWEIZEN
  - 159  # FRÜHKARTOFFELN / MAIS
  - 520  # FRÜHKARTOFFELN / FELDGEMÜSE
  - 524  # SPEISEKARTOFFELN
  - 526  # SPEISEKARTOFFELN / FELDGEMÜSE
  - 832  # HOLUNDER
  - 149  # EMMER ODER EINKORN (SOMMERUNG)
  - 151  # EMMER ODER EINKORN (SOMMERUNG) / FELDGEMÜSE
  - 150  # EMMER ODER EINKORN (WINTERUNG)
  - 152  # EMMER ODER EINKORN (WINTERUNG) / FELDGEMÜSE
  - 209  # ESPARSETTE
  - 202  # ACKERBOHNEN (PUFFBOHNEN)
  - 528  # FUTTERKARTOFFELN
  - 206  # ACKERBOHNEN - GETREIDE GEMENGE
  - 205  # ACKERBOHNEN (PUFFBOHNEN) / FELDGEMÜSE
  - 208  # ACKERBOHNEN / ERBSENGEMENGE
  - 210  # PELUSCHKE
  - 676  # FELDGEMÜSE EINLEGEGURKEN
  - 699  # FELDGEMÜSE FRISCHMARKT UND VERARBEITUNG MEHRKULTURIG
  - 694  # FELDGEMÜSE MEHRKULTURIG
  - 698  # FELDGEMÜSE VERARBEITUNG MEHRKULTURIG
  - 697  # FELDGEMÜSE VERARBEITUNG EINKULTURIG
  - 696  # FELDGEMÜSE EINKULTURIG
  - 653  # FELDGEMÜSE OHNE ERNTE
  - 626  # PLATTERBSEN
  - 657  # FLACHS (FASERLEIN) ZUR FASERERZEUGUNG
  - 310  # ÖLLEIN (NICHT ZUR FASERGEWINNUNG)
  - 525  # SPEISEINDUSTRIEKARTOFFELN
  - 631  # FUTTERRÜBEN (RUNKELRÜBEN, BURGUND KOHLRÜBEN)
  - 105  # KÖRNERMAIS
  - 201  # KÖRNERERBSEN
  - 204  # KÖRNERERBSEN / FELDGEMÜSE
  - 135  # GRÜNMAIS
  - 681  # GRÜNSCHNITTROGGEN
  - 764  # GRÜNSCHNITTROGGEN / MAIS
  - 765  # GRÜNSCHNITTROGGEN / HIRSE
  - 763  # GRÜNSCHNITTROGGEN / SUDANGRAS
  - 766  # GRÜNSCHNITTROGGEN / SONNENBLUME
  - 165  # WINTERHARTWEIZEN (DURUM)
  - 658  # HANF
  - 821  # HOPFEN
  - 622  # LINSEN
  - 680  # MARIENDISTELN
  - 538  # HEILPFLANZEN
  - 118  # HIRSE
  - 132  # HIRSE / FELDGEMÜSE  (not in 2020 data)
  - 506  # SENF
  - 311  # ÖLLEIN (NICHT ZUR FASERGEWINNUNG) / FELDGEMÜSE
  - 751  # ÖLKÜRBIS
  - 690  # ÖLRETTICH
  - 661  # SONSTIGE ACKERFLÄCHEN
  - 671  # SONSTIGE ACKERKULTUREN
  - 752  # SONSTIGE ÖLFRÜCHTE (SAFLOR, ...)
  - 129  # ERBSEN - GETREIDE GEMENGE / FELDGEMÜSE
  - 682  # PHACELIA
  - 768  # SPEISEKÜRBIS
  - 759  # QUINOA
  - 775  # SALBEI (CHIA)  (not in 2020 data)
  - 173  # SAATMAISVERMEHRUNG
  - 527  # SAATKARTOFFELN
  - 109  # SILOMAIS
  - 117  # SORGHUM
  - 308  # SOJABOHNEN
  - 309  # SOJABOHNEN / SOMMERWICKEN IN GETRENNTEN REIHEN
  - 540  # GEWÜRZFENCHEL
  - 539  # GEWÜRZPFLANZEN
  - 537  # JOHANNISKRAUT
  - 519  # STÄRKEINDUSTRIEKARTOFFELN
  - 755  # ERDBEEREN
  - 756  # ERDBEEREN / FELDGEMÜSE
  - 154  # SUDANGRAS
  - 651  # ZUCKERRÜBEN
  - 107  # ZUCKERMAIS
  - 134  # ZUCKERMAIS / FELDGEMÜSE
  - 111  # SOMMERGERSTE
  - 161  # SOMMERGERSTE / BUCHWEIZEN
  - 126  # SOMMERGERSTE / FELDGEMÜSE
  - 535  # SOMMERKÜMMEL
  - 128  # SOMMERMENGGETREIDE / FELDGEMÜSE
  - 137  # SOMMERWEICHWEIZEN
  - 166  # SOMMERHARTWEIZEN (DURUM)
  - 170  # SOMMERHARTWEIZEN (DURUM) / BUCHWEIZEN
  - 168  # SOMMERHARTWEIZEN (DURUM) / FELDGEMÜSE
  - 114  # SOMMERMENGGETREIDE
  - 155  # SOMMERHAFER
  - 156  # SOMMERHAFER / FELDGEMÜSE
  - 509  # SOMMERMOHN
  - 302  # SOMMERRAPS
  - 141  # SOMMERROGGEN
  - 143  # SOMMERROGGEN / FELDGEMÜSE
  - 146  # SOMMERDINKEL (SPELZ)
  - 157  # SOMMERTRITICALE
  - 624  # SOMMERWICKEN
  - 307  # SONNENBLUMEN
  - 203  # SÜSSLUPINEN
  - 769  # TOPINAMBUR
  - 638  # WICKEN - GETREIDE GEMENGE
  - 110  # WINTERGERSTE
  - 153  # WINTERGERSTE / BUCHWEIZEN
  - 178  # WINTERGERSTE/KLEE
  - 176  # WINTERGERSTE/KLEEGRAS
  - 125  # WINTERGERSTE / FELDGEMÜSE
  - 175  # WINTERGERSTE/KÖRNERMAIS
  - 174  # WINTERGERSTE/SILOMAIS
  - 776  # WINTERGERSTE/SOJABOHNEN  (not in 2020 data)
  - 303  # WINTERRÜBSEN
  - 536  # WINTERKÜMMEL
  - 127  # WINTERMENGGETREIDE / FELDGEMÜSE
  - 167  # WINTERHARTWEIZEN (DURUM) / FELDGEMÜSE
  - 169  # WINTERHARTWEIZEN (DURUM) / BUCHWEIZEN
  - 113  # WINTERMENGGETREIDE
  - 112  # WINTERHAFER
  - 510  # WINTERMOHN
  - 301  # WINTERRAPS
  - 142  # WINTERROGGEN
  - 144  # WINTERROGGEN / FELDGEMÜSE
  - 138  # WINTERWEICHWEIZEN
  - 140  # WINTERWEICHWEIZEN / FELDGEMÜSE
  - 145  # WINTERDINKEL (SPELZ)
  - 148  # WINTERDINKEL (SPELZ) / FELDGEMÜSE
  - 116  # WINTERTRITICALE
  - 130  # WINTERTRITICALE / FELDGEMÜSE
  - 162  # WINTERTRITICALE / FUTTERRÜBE
  - 171  # WINTERTRITICALE / HIRSE
  - 625  # WINTERWICKEN
  - 160  # WINTERWEICHWEIZEN / BUCHWEIZEN
  - 115  # ERBSEN - GETREIDE GEMENGE
  - 158  # SOMMERTRITICALE / FELDGEMÜSE
  - 164  # ERBSEN - GETREIDE GEMENGE / BUCHWEIZEN

exclude:
  - 920  # NATURSCHUTZFACHLICH WERTVOLLE PFLEGEFLÄCHE
  - 351  # LSE HECKE / UFERGEHÖLZ
  - 959  # 20 JÄHRIGE STILLLEGUNG
  - 990  # ALMFUTTERFLÄCHE
  - 636  # WECHSELWIESE (EGART, ACKERWEIDE)
  - 813  # MARILLEN
  - 773  # BIENENTRACHTBRACHE
  - 812  # KIRSCHEN
  - 906  # SCHNITTWEINGARTEN
  - 352  # GLÖZ GRABEN / UFERRANDSTREIFEN
  - 686  # ELEFANTENGRAS (CHINASCHILF, MISCANTHUS SINENSIS)
  - 641  # ENERGIEGRAS
  - 864  # ENERGIEHOLZ ROBINIE
  - 863  # ENERGIEHOLZ OHNE ROBINIE
  - 964  # ERSTAUFFORSTUNG ALT
  - 654  # BLUMEN UND ZIERPFLANZEN
  - 838  # BLUMEN UND ZIERPFLANZEN IM FOLIENTUNNEL
  - 837  # BLUMEN UND ZIERPFLANZEN IM GEWÄCHSHAUS
  - 637  # FUTTERGRÄSER
  - 663  # FUTTERGRÄSER / FELDGEMÜSE
  - 965  # FORST GENETISCHE RESSOURCEN
  - 806  # OBST/HOPFEN BODENGESUNDUNG
  - 852  # OBST IM FOLIENTUNNEL
  - 851  # OBST IM GEWÄCHSHAUS
  - 772  # GINKGO
  - 960  # WALDUMWELTMASSNAHMEN
  - 354  # GLÖZ STEINRIEGEL / STEINHAGE
  - 771  # GRÜNBRACHE
  - 704  # STREUWIESE
  - 707  # HUTWEIDE
  - 848  # HEILPFLANZEN IM FOLIENTUNNEL
  - 847  # HEILPFLANZEN IM GEWÄCHSHAUS  (not in 2020 data)
  - 708  # BERGMÄHDER
  - 717  # MÄHWIESE/-WEIDE DREI UND MEHR NUTZUNGEN
  - 716  # MÄHWIESE/-WEIDE ZWEI NUTZUNGEN
  - 861  # MEHRJÄHRIGE BAUMSCHULEN
  - 358  # GLÖZ NATURDENKMAL FLÄCHE
  - 829  # NEKTARINEN
  - 844  # EDELKASTANIEN
  - 842  # SCHALENFRÜCHTE (WALNÜSSE, HASELNÜSSE, ...)
  - 860  # EINJÄHRIGE BAUMSCHULEN
  - 701  # EINMÄHDIGE WIESE
  - 843  # SONSTIGE FLÄCHEN: GESCHÜTZTER ANBAU
  - 846  # SONSTIGE KULTUREN IM FOLIENTUNNEL
  - 845  # SONSTIGE KULTUREN IM GEWÄCHSHAUS
  - 679  # SONSTIGES FELDFUTTER
  - 809  # ANDERES OBST
  - 710  # SONSTIGE GRÜNLANDFLÄCHEN
  - 722  # SONSTIGE HUTWEIDEFLÄCHEN
  - 865  # ANDERE DAUERKULTUREN
  - 810  # SONSTIGE SPEZIALKULTURFLÄCHEN
  - 907  # SONSTIGE WEINFLÄCHEN
  - 814  # PFIRSICHE
  - 715  # DAUERWEIDE
  - 830  # PFLAUMEN
  - 820  # ZWETSCHKEN
  - 355  # GLÖZ TEICH / TÜMPEL
  - 961  # ERSTAUFFORSTUNG
  - 353  # LSE RAIN / BÖSCHUNG / TROCKENSTEINMAUER
  - 350  # LSE FELDGEHÖLZ / BAUM- / GEBÜSCHGRUPPE
  - 828  # QUITTEN
  - 831  # STRAUCHBEEREN
  - 819  # WEICHSELN
  - 850  # GEWÜRZPFLANZEN IM FOLIENTUNNEL
  - 849  # GEWÜRZPFLANZEN IM GEWÄCHSHAUS
  - 817  # TAFELÄPFEL
  - 818  # TAFELBIRNEN
  - 767  # ROLLRASEN
  - 840  # GEMÜSE IM FOLIENTUNNEL
  - 839  # GEMÜSE IM GEWÄCHSHAUS
  - 862  # REBSCHULEN
  - 901  # WEIN
  - 902  # WEIN BODENGESUNDUNG
  - 177  # WINTERGERSTE/FUTTERGRÄSER
  - 721  # GRÜNLANDBRACHE
